-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jun 24, 2023 at 09:45 AM
-- Server version: 8.0.31
-- PHP Version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `itec_project`
--

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

DROP TABLE IF EXISTS `posts`;
CREATE TABLE IF NOT EXISTS `posts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `views` int NOT NULL DEFAULT '0',
  `image` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `published` tinyint(1) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `posted_time` timestamp NULL DEFAULT NULL,
  `type` enum('LIFESTYLE','FOOD','NATURE','PHOTOGRAPHY') DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `user_id`, `title`, `slug`, `views`, `image`, `body`, `published`, `created_at`, `updated_at`, `posted_time`, `type`) VALUES
(4, 1, 'Unveiling the Secrets: 10 Proven Strategies for Success1', 'title-1', 100, 'post_image1.webp', 'This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.\nThis blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.\nThis blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 09:37:17', '0000-00-00 00:00:00', '2015-12-31 17:00:00', 'LIFESTYLE'),
(5, 1, 'The Ultimate Guide to Mastering Productivity', 'title-2', 200, 'post_image2.webp', 'Fake All is a fake social media generator for iPhone instead that lets you create fake calls, messages, and WhatsApp chats in an instant. Whether you want to generate one for social media or get a call to get out of an awkward gathering, this app does it all. You can create a fake call from anyone and set a timer. As soon as the timer goes off, you’d get a call which you can even pick up and pretend to talk.\nThis blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.\n', 1, '2023-06-21 09:37:21', '0000-00-00 00:00:00', '2006-12-31 17:00:00', 'LIFESTYLE'),
(6, 2, 'Unlocking Your Creativity: Innovative Approaches for Inspired Living', 'title-50', 500, 'post_image5.webp', 'This next app lets you generate fake Tinder profiles with comprehensive details. You can add multiple photos, bio, work, age, distance, and even get an “It’s a Match!” screen. The app is really precise and gives out impeccable results. It is free and ad-supported.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 23:52:23', '0000-00-00 00:00:00', '2008-12-31 17:00:00', 'FOOD'),
(43, 1, 'Journey to Self-Discovery: Finding Your True Purpose', 'title-4', 300, 'post_image4.webp', 'Social Dummy is an all-in-one app that can generate a fake social media screenshot of almost any app that you may want. You can create fake Twitter, iMessage, Instagram, YouTube, Facebook, Tumblr, Snapchat, FaceTime, WhatsApp, Call, Spotify, Netflix, Safari, and even the Lock Screen.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 09:37:25', '0000-00-00 00:00:00', '2004-12-31 17:00:00', 'FOOD'),
(44, 1, 'Revolutionizing the Way We Work: Future Trends and Technologies', 'title-5', 250, 'post_image5.webp', 'Prankmenot is a web service that allows you to create fake tweets and Facebook posts. The interface is simple. You get all the controls on the left that allow you to feed information. For example, when creating a fake tweet, you would be able to change the DP, edit the tweet body, change the username, and even set the date.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 09:37:27', '0000-00-00 00:00:00', '2018-12-31 17:00:00', 'FOOD'),
(45, 2, 'The Art of Mindfulness: Cultivating Inner Peace in a Chaotic World', 'title-6', 400, 'post_image6.webp', 'This next service offers quite a few different tools to generate fake posts for Instagram, Facebook, Snapchat, and Twitter. Instead of offering to create posts, GenerateStatus can also create fake profile pages and fake chat conversations in the respective apps.\n\n', 1, '2023-06-21 09:37:30', '0000-00-00 00:00:00', '2017-12-31 17:00:00', 'NATURE'),
(46, 2, 'Exploring the Wonders of Nature: A Photographic Adventure', 'title-7', 200, 'post_image7.webp', 'Yahoo Answers is a community-driven Q&A site where people ask genuine questions and receive insightful answers. However, there have been times when people have found hilarious answers to stupid questions. Simitators offers an easy way to simulate that and create a fake scenario with funny answers.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 09:37:34', '0000-00-00 00:00:00', '2016-12-31 17:00:00', 'NATURE'),
(47, 2, 'The Power of Authentic Leadership: Inspiring Change and Impact', 'title-8', 350, 'post_image8.webp', 'Zeoob is an all-in-one website that lets you generate fake posts and chats for Snapchat, Twitter, Facebook, iMessage, WhatsApp, and Instagram. The interface is really polished for not only web but also mobile views. I mainly use it to create iMessage chats where you can change your carrier, name, timestamp, header, footer, and chat bubbles.\nThis blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.\n', 1, '2023-06-21 09:37:37', '0000-00-00 00:00:00', '2007-12-31 17:00:00', 'NATURE'),
(48, 2, 'From Dreams to Reality: Turning Ideas into Thriving Businesses', 'title-9', 450, 'post_image9.webp', 'These were a few apps and services that you can use to create fake social media posts and chats. I’ve tried to cover every popular messaging and social media app but if I’ve missed something then let me know by shooting a tweet at me.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 09:37:40', '0000-00-00 00:00:00', '2011-12-31 17:00:00', 'NATURE'),
(49, 2, 'Living a Balanced Life: Nurturing Wellness in Mind, Body, and Soul', 'title-10', 250, 'post_image10.webp', 'Works as an in-house Writer at TechWiser and focuses on the latest smart consumer electronics. Closely follows the latest trends in consumer IoT and how it affects our daily lives. You can follow him on Twitter. Yes, he sometimes speaks in Third Person.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 14:02:58', '0000-00-00 00:00:00', '2015-12-31 17:00:00', 'NATURE'),
(50, 3, 'Breaking Barriers: Empowering Women in the Modern World', 'title-11', 300, 'post_image11.webp', 'If you don’t have a presence on social media, you’re missing a prime opportunity to reach new prospects for your business. Considering that 74% of people use social media when making purchasing decisions, you don’t want to miss an opportunity to help nudge them towards buying your products. But if you’re unfamiliar with social media, it may feel like a daunting task to figure it out.\n\nOur social media 101 guide can help, as we cover critical information like:This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 09:37:46', '0000-00-00 00:00:00', '2005-12-31 17:00:00', 'PHOTOGRAPHY'),
(51, 3, 'The Science of Happiness: Unleashing Joy and Fulfillment', 'title-12', 400, 'post_image12.webp', 'Before we dive into the social media basics, let’s cover the reasons why you’ll want to use social media for your business:\n\n1. Social media helps you build relationships\nSocial media is an excellent place for you to build relationships with prospects interested in the products and services you offer. It provides you with a medium to engage one-on-one with prospects through features like direct messaging and commenting on content posts. Building relationships and communities are valuable for helping your business grow online.\n\nWhen people know your business and feel comfortablThis blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 09:37:49', '0000-00-00 00:00:00', '2000-12-31 17:00:00', 'PHOTOGRAPHY'),
(52, 3, 'Mastering the Art of Communication: Building Meaningful Connections', 'title-13', 200, 'post_image13.webp', 'Brand awareness is fundamental to help you earn prospects for your business. When people connect with you on social media, they learn who you are and what you offer. Social media enables you to put your brand in front of prospects.\n\nYou can post content that appears in your followers’ newsfeeds and encourage your followers to share your content with people that follow them. It helps you take up more online real estate, which in turn, leads to more people seeing your business and increasing brand awareness.', 1, '2023-06-21 09:37:51', '0000-00-00 00:00:00', '2006-12-31 17:00:00', 'PHOTOGRAPHY'),
(53, 3, 'Innovations Shaping the Future: Technology at the Forefront', 'title-14', 500, 'post_image14.webp', 'Social media is a valuable avenue for you to increase traffic from social networks on your company’s website. When you create a social media profile on any number of channels, you can share links to your website and encourage users to visit pages on your site. As a result, more people spend time reading your blog posts, checking out your products, or learning about your services.\n\nThis blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.', 1, '2023-06-21 09:37:54', '0000-00-00 00:00:00', '2011-12-31 17:00:00', 'PHOTOGRAPHY'),
(54, 3, 'Sustainable Living: Eco-Friendly Practices for a Greener Planet', 'title-15', 350, 'post_image15.webp', 'Next in our guide of social media basics is the social media platforms you can choose from. There are dozens of social media platforms you can use to grow your business online. Here are some of the most popular social platforms you can use to grow your business:\n\nNext in our guide of social media basics is the social media platforms you can choose from. There are dozens of social media platforms you can use to grow your business online. Here are some of the most popular social platforms you can use to grow your business:\nThis blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.This blog post delves into ten tried and tested strategies that can pave the way for success in various aspects of life. It explores valuable insights, tips, and techniques backed by research and real-world experiences.\n', 1, '2023-06-21 09:37:57', '0000-00-00 00:00:00', '2000-12-31 17:00:00', 'PHOTOGRAPHY'),
(70, 1, 'Post Title 70', 'post-title-70', 0, 'image70.webp', 'This is the content of post 70.', 0, '2023-06-21 14:52:42', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(71, 1, 'Post Title 71', 'post-title-71', 0, 'image71.webp', 'This is the content of post 71.', 0, '2023-06-21 14:53:44', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(72, 1, 'Post Title 72', 'post-title-72', 0, 'image72.webp', 'This is the content of post 72.', 0, '2023-06-21 14:53:46', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(73, 1, 'Post Title 73', 'post-title-73', 0, 'image73.webp', 'This is the content of post 73.', 0, '2023-06-21 14:53:50', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(74, 1, 'Post Title 74', 'post-title-74', 0, 'image74.webp', 'This is the content of post 74.', 0, '2023-06-21 14:53:52', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(75, 1, 'Post Title 75', 'post-title-75', 0, 'image75.webp', 'This is the content of post 75.', 0, '2023-06-21 14:53:55', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(76, 1, 'Post Title 76', 'post-title-76', 0, 'image76.webp', 'This is the content of post 76.', 0, '2023-06-21 14:53:57', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(77, 1, 'Post Title 77', 'post-title-77', 0, 'image77.webp', 'This is the content of post 77.', 0, '2023-06-21 14:54:01', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(78, 1, 'Post Title 78', 'post-title-78', 0, 'image78.webp', 'This is the content of post 78.', 0, '2023-06-21 14:54:03', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(79, 1, 'Post Title 79', 'post-title-79', 0, 'image79.webp', 'This is the content of post 79.', 0, '2023-06-21 14:54:07', '0000-00-00 00:00:00', NULL, 'LIFESTYLE'),
(80, 1, 'Post Title 80', 'post-title-80', 0, 'image80.webp', 'This is the content of post 80.', 0, '2023-06-21 23:47:19', '0000-00-00 00:00:00', NULL, 'LIFESTYLE');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `posts`
--
ALTER TABLE `posts`
  ADD CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
